# Generated by Django 5.2.4 on 2025-07-04 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_receita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita_medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.CharField(max_length=50)),
                ('frequencia', models.CharField(max_length=50)),
                ('duracao', models.CharField(max_length=50)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to='clinica.medicamento')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_receitados', to='clinica.receita')),
            ],
        ),
    ]
